nombre:  Construir 
en: 
  empujar: 
    ramas: 
      -  principal 
  pull_request: 
    tipos: [ abierto , sincronizar , reabierto ]
 trabajos: 
  sonarqube: 
    nombre:  SonarQube 
    se ejecuta en:  windows-latest 
    pasos: 
      -  usos:  acciones/checkout@v4 
        con: 
          fetch-depth:  0   # Los clones superficiales deben estar deshabilitados para una mejor relevancia del análisis 
      -  nombre:  SonarQube  Scan 
        usos:  SonarSource/sonarqube-scan-action@v5 
        env: 
          SONAR_TOKEN:  ${{  secrets.SONAR_TOKEN  }}
